//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFSWS.Test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.HFSWSSoap")]
    public interface HFSWSSoap {
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HisTransData", ReplyAction="*")]
        HFSWS.Test.ServiceReference1.HisTransDataResponse HisTransData(HFSWS.Test.ServiceReference1.HisTransDataRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deal_dept", ReplyAction="*")]
        HFSWS.Test.ServiceReference1.deal_deptResponse deal_dept(HFSWS.Test.ServiceReference1.deal_deptRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deal_employee", ReplyAction="*")]
        HFSWS.Test.ServiceReference1.deal_employeeResponse deal_employee(HFSWS.Test.ServiceReference1.deal_employeeRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deal_drug", ReplyAction="*")]
        HFSWS.Test.ServiceReference1.deal_drugResponse deal_drug(HFSWS.Test.ServiceReference1.deal_drugRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deal_undrug", ReplyAction="*")]
        HFSWS.Test.ServiceReference1.deal_undrugResponse deal_undrug(HFSWS.Test.ServiceReference1.deal_undrugRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deal_material", ReplyAction="*")]
        HFSWS.Test.ServiceReference1.deal_materialResponse deal_material(HFSWS.Test.ServiceReference1.deal_materialRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deal_provider", ReplyAction="*")]
        HFSWS.Test.ServiceReference1.deal_providerResponse deal_provider(HFSWS.Test.ServiceReference1.deal_providerRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deal_manufactorer", ReplyAction="*")]
        HFSWS.Test.ServiceReference1.deal_manufactorerResponse deal_manufactorer(HFSWS.Test.ServiceReference1.deal_manufactorerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HisTransDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HisTransData", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.HisTransDataRequestBody Body;
        
        public HisTransDataRequest() {
        }
        
        public HisTransDataRequest(HFSWS.Test.ServiceReference1.HisTransDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HisTransDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public HisTransDataRequestBody() {
        }
        
        public HisTransDataRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HisTransDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HisTransDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.HisTransDataResponseBody Body;
        
        public HisTransDataResponse() {
        }
        
        public HisTransDataResponse(HFSWS.Test.ServiceReference1.HisTransDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HisTransDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HisTransDataResult;
        
        public HisTransDataResponseBody() {
        }
        
        public HisTransDataResponseBody(string HisTransDataResult) {
            this.HisTransDataResult = HisTransDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_deptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_dept", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_deptRequestBody Body;
        
        public deal_deptRequest() {
        }
        
        public deal_deptRequest(HFSWS.Test.ServiceReference1.deal_deptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_deptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public deal_deptRequestBody() {
        }
        
        public deal_deptRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_deptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_deptResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_deptResponseBody Body;
        
        public deal_deptResponse() {
        }
        
        public deal_deptResponse(HFSWS.Test.ServiceReference1.deal_deptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_deptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deal_deptResult;
        
        public deal_deptResponseBody() {
        }
        
        public deal_deptResponseBody(string deal_deptResult) {
            this.deal_deptResult = deal_deptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_employeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_employee", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_employeeRequestBody Body;
        
        public deal_employeeRequest() {
        }
        
        public deal_employeeRequest(HFSWS.Test.ServiceReference1.deal_employeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_employeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public deal_employeeRequestBody() {
        }
        
        public deal_employeeRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_employeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_employeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_employeeResponseBody Body;
        
        public deal_employeeResponse() {
        }
        
        public deal_employeeResponse(HFSWS.Test.ServiceReference1.deal_employeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_employeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deal_employeeResult;
        
        public deal_employeeResponseBody() {
        }
        
        public deal_employeeResponseBody(string deal_employeeResult) {
            this.deal_employeeResult = deal_employeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_drugRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_drug", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_drugRequestBody Body;
        
        public deal_drugRequest() {
        }
        
        public deal_drugRequest(HFSWS.Test.ServiceReference1.deal_drugRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_drugRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public deal_drugRequestBody() {
        }
        
        public deal_drugRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_drugResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_drugResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_drugResponseBody Body;
        
        public deal_drugResponse() {
        }
        
        public deal_drugResponse(HFSWS.Test.ServiceReference1.deal_drugResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_drugResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deal_drugResult;
        
        public deal_drugResponseBody() {
        }
        
        public deal_drugResponseBody(string deal_drugResult) {
            this.deal_drugResult = deal_drugResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_undrugRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_undrug", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_undrugRequestBody Body;
        
        public deal_undrugRequest() {
        }
        
        public deal_undrugRequest(HFSWS.Test.ServiceReference1.deal_undrugRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_undrugRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public deal_undrugRequestBody() {
        }
        
        public deal_undrugRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_undrugResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_undrugResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_undrugResponseBody Body;
        
        public deal_undrugResponse() {
        }
        
        public deal_undrugResponse(HFSWS.Test.ServiceReference1.deal_undrugResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_undrugResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deal_undrugResult;
        
        public deal_undrugResponseBody() {
        }
        
        public deal_undrugResponseBody(string deal_undrugResult) {
            this.deal_undrugResult = deal_undrugResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_materialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_material", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_materialRequestBody Body;
        
        public deal_materialRequest() {
        }
        
        public deal_materialRequest(HFSWS.Test.ServiceReference1.deal_materialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_materialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public deal_materialRequestBody() {
        }
        
        public deal_materialRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_materialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_materialResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_materialResponseBody Body;
        
        public deal_materialResponse() {
        }
        
        public deal_materialResponse(HFSWS.Test.ServiceReference1.deal_materialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_materialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deal_materialResult;
        
        public deal_materialResponseBody() {
        }
        
        public deal_materialResponseBody(string deal_materialResult) {
            this.deal_materialResult = deal_materialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_providerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_provider", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_providerRequestBody Body;
        
        public deal_providerRequest() {
        }
        
        public deal_providerRequest(HFSWS.Test.ServiceReference1.deal_providerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_providerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public deal_providerRequestBody() {
        }
        
        public deal_providerRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_providerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_providerResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_providerResponseBody Body;
        
        public deal_providerResponse() {
        }
        
        public deal_providerResponse(HFSWS.Test.ServiceReference1.deal_providerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_providerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deal_providerResult;
        
        public deal_providerResponseBody() {
        }
        
        public deal_providerResponseBody(string deal_providerResult) {
            this.deal_providerResult = deal_providerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_manufactorerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_manufactorer", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_manufactorerRequestBody Body;
        
        public deal_manufactorerRequest() {
        }
        
        public deal_manufactorerRequest(HFSWS.Test.ServiceReference1.deal_manufactorerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_manufactorerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public deal_manufactorerRequestBody() {
        }
        
        public deal_manufactorerRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deal_manufactorerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deal_manufactorerResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFSWS.Test.ServiceReference1.deal_manufactorerResponseBody Body;
        
        public deal_manufactorerResponse() {
        }
        
        public deal_manufactorerResponse(HFSWS.Test.ServiceReference1.deal_manufactorerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deal_manufactorerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deal_manufactorerResult;
        
        public deal_manufactorerResponseBody() {
        }
        
        public deal_manufactorerResponseBody(string deal_manufactorerResult) {
            this.deal_manufactorerResult = deal_manufactorerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HFSWSSoapChannel : HFSWS.Test.ServiceReference1.HFSWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HFSWSSoapClient : System.ServiceModel.ClientBase<HFSWS.Test.ServiceReference1.HFSWSSoap>, HFSWS.Test.ServiceReference1.HFSWSSoap {
        
        public HFSWSSoapClient() {
        }
        
        public HFSWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HFSWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HFSWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HFSWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFSWS.Test.ServiceReference1.HisTransDataResponse HFSWS.Test.ServiceReference1.HFSWSSoap.HisTransData(HFSWS.Test.ServiceReference1.HisTransDataRequest request) {
            return base.Channel.HisTransData(request);
        }
        
        public string HisTransData(string xml) {
            HFSWS.Test.ServiceReference1.HisTransDataRequest inValue = new HFSWS.Test.ServiceReference1.HisTransDataRequest();
            inValue.Body = new HFSWS.Test.ServiceReference1.HisTransDataRequestBody();
            inValue.Body.xml = xml;
            HFSWS.Test.ServiceReference1.HisTransDataResponse retVal = ((HFSWS.Test.ServiceReference1.HFSWSSoap)(this)).HisTransData(inValue);
            return retVal.Body.HisTransDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFSWS.Test.ServiceReference1.deal_deptResponse HFSWS.Test.ServiceReference1.HFSWSSoap.deal_dept(HFSWS.Test.ServiceReference1.deal_deptRequest request) {
            return base.Channel.deal_dept(request);
        }
        
        public string deal_dept(string xml) {
            HFSWS.Test.ServiceReference1.deal_deptRequest inValue = new HFSWS.Test.ServiceReference1.deal_deptRequest();
            inValue.Body = new HFSWS.Test.ServiceReference1.deal_deptRequestBody();
            inValue.Body.xml = xml;
            HFSWS.Test.ServiceReference1.deal_deptResponse retVal = ((HFSWS.Test.ServiceReference1.HFSWSSoap)(this)).deal_dept(inValue);
            return retVal.Body.deal_deptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFSWS.Test.ServiceReference1.deal_employeeResponse HFSWS.Test.ServiceReference1.HFSWSSoap.deal_employee(HFSWS.Test.ServiceReference1.deal_employeeRequest request) {
            return base.Channel.deal_employee(request);
        }
        
        public string deal_employee(string xml) {
            HFSWS.Test.ServiceReference1.deal_employeeRequest inValue = new HFSWS.Test.ServiceReference1.deal_employeeRequest();
            inValue.Body = new HFSWS.Test.ServiceReference1.deal_employeeRequestBody();
            inValue.Body.xml = xml;
            HFSWS.Test.ServiceReference1.deal_employeeResponse retVal = ((HFSWS.Test.ServiceReference1.HFSWSSoap)(this)).deal_employee(inValue);
            return retVal.Body.deal_employeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFSWS.Test.ServiceReference1.deal_drugResponse HFSWS.Test.ServiceReference1.HFSWSSoap.deal_drug(HFSWS.Test.ServiceReference1.deal_drugRequest request) {
            return base.Channel.deal_drug(request);
        }
        
        public string deal_drug(string xml) {
            HFSWS.Test.ServiceReference1.deal_drugRequest inValue = new HFSWS.Test.ServiceReference1.deal_drugRequest();
            inValue.Body = new HFSWS.Test.ServiceReference1.deal_drugRequestBody();
            inValue.Body.xml = xml;
            HFSWS.Test.ServiceReference1.deal_drugResponse retVal = ((HFSWS.Test.ServiceReference1.HFSWSSoap)(this)).deal_drug(inValue);
            return retVal.Body.deal_drugResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFSWS.Test.ServiceReference1.deal_undrugResponse HFSWS.Test.ServiceReference1.HFSWSSoap.deal_undrug(HFSWS.Test.ServiceReference1.deal_undrugRequest request) {
            return base.Channel.deal_undrug(request);
        }
        
        public string deal_undrug(string xml) {
            HFSWS.Test.ServiceReference1.deal_undrugRequest inValue = new HFSWS.Test.ServiceReference1.deal_undrugRequest();
            inValue.Body = new HFSWS.Test.ServiceReference1.deal_undrugRequestBody();
            inValue.Body.xml = xml;
            HFSWS.Test.ServiceReference1.deal_undrugResponse retVal = ((HFSWS.Test.ServiceReference1.HFSWSSoap)(this)).deal_undrug(inValue);
            return retVal.Body.deal_undrugResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFSWS.Test.ServiceReference1.deal_materialResponse HFSWS.Test.ServiceReference1.HFSWSSoap.deal_material(HFSWS.Test.ServiceReference1.deal_materialRequest request) {
            return base.Channel.deal_material(request);
        }
        
        public string deal_material(string xml) {
            HFSWS.Test.ServiceReference1.deal_materialRequest inValue = new HFSWS.Test.ServiceReference1.deal_materialRequest();
            inValue.Body = new HFSWS.Test.ServiceReference1.deal_materialRequestBody();
            inValue.Body.xml = xml;
            HFSWS.Test.ServiceReference1.deal_materialResponse retVal = ((HFSWS.Test.ServiceReference1.HFSWSSoap)(this)).deal_material(inValue);
            return retVal.Body.deal_materialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFSWS.Test.ServiceReference1.deal_providerResponse HFSWS.Test.ServiceReference1.HFSWSSoap.deal_provider(HFSWS.Test.ServiceReference1.deal_providerRequest request) {
            return base.Channel.deal_provider(request);
        }
        
        public string deal_provider(string xml) {
            HFSWS.Test.ServiceReference1.deal_providerRequest inValue = new HFSWS.Test.ServiceReference1.deal_providerRequest();
            inValue.Body = new HFSWS.Test.ServiceReference1.deal_providerRequestBody();
            inValue.Body.xml = xml;
            HFSWS.Test.ServiceReference1.deal_providerResponse retVal = ((HFSWS.Test.ServiceReference1.HFSWSSoap)(this)).deal_provider(inValue);
            return retVal.Body.deal_providerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFSWS.Test.ServiceReference1.deal_manufactorerResponse HFSWS.Test.ServiceReference1.HFSWSSoap.deal_manufactorer(HFSWS.Test.ServiceReference1.deal_manufactorerRequest request) {
            return base.Channel.deal_manufactorer(request);
        }
        
        public string deal_manufactorer(string xml) {
            HFSWS.Test.ServiceReference1.deal_manufactorerRequest inValue = new HFSWS.Test.ServiceReference1.deal_manufactorerRequest();
            inValue.Body = new HFSWS.Test.ServiceReference1.deal_manufactorerRequestBody();
            inValue.Body.xml = xml;
            HFSWS.Test.ServiceReference1.deal_manufactorerResponse retVal = ((HFSWS.Test.ServiceReference1.HFSWSSoap)(this)).deal_manufactorer(inValue);
            return retVal.Body.deal_manufactorerResult;
        }
    }
}
